### Sampling for Train-Val-Test set
### Controlled for topics: no topics can fall in the train & val or train & test sets
### topics in both the val & test sets is fine
### Due to lack of A1, A1+, C2, C2+ texts, I only included A2 to C1+

In [1]:
import pandas as pd 

# read in tsv file
input_df = pd.read_csv('en-writeandimprove2024-corpus.tsv', sep='\t')
# add topic and genre columns
# read in a tsv file
topic_genre = pd.read_csv("en-writeandimprove2024-prompts-info.tsv", sep="\t")


# in input_df, add topic and genre columns based on public_prompt_id in topic_genre
# Select only the needed columns from topic_genre
cols_to_keep = ["public_prompt_id", "topic", "genre", "prompt"]

df = input_df.drop(columns=["topic", "genre"], errors="ignore").merge(
    topic_genre[cols_to_keep],
    on="public_prompt_id",
    how="left"
)
df

,public_essay_id,created_epoch,created_timestamp,public_prompt_id,public_user_id,user_prompt,essay_version_num,is_first_version,is_final_version,language,text,wi_suspecttokens,automarker_cefr_level,humannotator_cefr_level,split,topic,genre,prompt
0,essay_304592203663ec1b,1577449947,2019-12-27 12:32:27,prompt_305b51299790d8a8,user_30e107f263a61611,user_30e107f263a61611_prompt_305b51299790d8a8,1,True,False,Japanese,"My favorite season is autumn. First, there ar...",NaN,B1,NaN,train,My favourite season of the year,An article,You have been asked to write a short __article...
1,essay_e4126fe7e70cae9e,1577752462,2019-12-31 00:34:22,prompt_305b51299790d8a8,user_30e107f263a61611,user_30e107f263a61611_prompt_305b51299790d8a8,2,False,False,Japanese,"My favorite season is autumn. First, there ar...","190,197",B1,NaN,NaN,My favourite season of the year,An article,You have been asked to write a short __article...
2,essay_40a9a64bebc02d79,1577752769,2019-12-31 00:39:29,prompt_305b51299790d8a8,user_30e107f263a61611,user_30e107f263a61611_prompt_305b51299790d8a8,3,False,False,Japanese,"My favorite season is autumn. First, there ar...",NaN,B1+,NaN,NaN,My favourite season of the year,An article,You have been asked to write a short __article...
3,essay_98851f65614be0df,1577760174,2019-12-31 02:42:54,prompt_305b51299790d8a8,user_30e107f263a61611,user_30e107f263a61611_prompt_305b51299790d8a8,4,False,False,Japanese,"My favorite season is autumn. First, there ar...",NaN,B1+,NaN,NaN,My favourite season of the year,An article,You have been asked to write a short __article...
4,essay_49777cdbbb998023,1577760292,2019-12-31 02:44:52,prompt_305b51299790d8a8,user_30e107f263a61611,user_30e107f263a61611_prompt_305b51299790d8a8,5,False,False,Japanese,"My favorite season is autumn. First, there ar...",NaN,B1+,NaN,NaN,My favourite season of the year,An article,You have been asked to write a short __article...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23211,essay_a7f33281e3d21749,1672405740,2022-12-30 13:09:00,prompt_82f61f70f00cce70,user_66b7fe0ceb2d039d,user_66b7fe0ceb2d039d_prompt_82f61f70f00cce70,7,False,False,Vietnamese,"In my opinion, I agree with the statement belo...",NaN,C1,NaN,NaN,Books and technology,An opinion essay,Should computers and tablets completely replac...
23212,essay_a7de0d23a388aa3d,1672405754,2022-12-30 13:09:14,prompt_82f61f70f00cce70,user_66b7fe0ceb2d039d,user_66b7fe0ceb2d039d_prompt_82f61f70f00cce70,8,False,False,Vietnamese,"In my opinion, I agree with the statement belo...",NaN,C1,NaN,NaN,Books and technology,An opinion essay,Should computers and tablets completely replac...
23213,essay_c689fa9de0099ed6,1672405848,2022-12-30 13:10:48,prompt_82f61f70f00cce70,user_66b7fe0ceb2d039d,user_66b7fe0ceb2d039d_prompt_82f61f70f00cce70,9,False,True,Vietnamese,"In my opinion, I agree with the statement belo...",NaN,C1+,B2,train,Books and technology,An opinion essay,Should computers and tablets completely replac...
23214,essay_5abd0f782265c28a,1672469971,2022-12-31 06:59:31,prompt_d5dbd9c04a5c932d,user_43a76f3854bac326,user_43a76f3854bac326_prompt_d5dbd9c04a5c932d,1,True,False,Chinese,Music i...,"488,492,757,762",B2,NaN,train,Music in our lives,An article,You have seen this notice in an international ...
23215,essay_7022cad7218fbf03,1672473905,2022-12-31 08:05:05,prompt_d5dbd9c04a5c932d,user_43a76f3854bac326,user_43a76f3854bac326_prompt_d5dbd9c04a5c932d,2,False,True,Chinese,Music i...,NaN,B2,B2,train,Music in our lives,An article,You have seen this notice in an international ...

In [2]:
# select all rows where humannotator_cefr_level is not null
# It seems like the final essay attempt has the human annotation
df_cefr = df[df['humannotator_cefr_level'].notnull()]
df_cefr

,public_essay_id,created_epoch,created_timestamp,public_prompt_id,public_user_id,user_prompt,essay_version_num,is_first_version,is_final_version,language,text,wi_suspecttokens,automarker_cefr_level,humannotator_cefr_level,split,topic,genre,prompt
22,essay_28aba35720851372,1577885043,2020-01-01 13:24:03,prompt_e4c497f7613dcf8a,user_e48ee201eb41c367,user_e48ee201eb41c367_prompt_e4c497f7613dcf8a,3,False,True,Portuguese,New Year is always an invite to establish goal...,NaN,B2+,B1+,train,A new school year,A report,It is the start of a new school year at your s...
27,essay_de0d459ad84b20be,1577927913,2020-01-02 01:18:33,prompt_40037060180c75db,user_4024872408b949a3,user_4024872408b949a3_prompt_40037060180c75db,5,False,True,Vietnamese,"In addition to studying at university, I have...",NaN,B1,B1,test,What you do in your free time,An essay,Your teacher asks you to write about what you ...
35,essay_39e931900d165aff,1577951710,2020-01-02 07:55:10,prompt_98e191fa5bded725,user_988d09923a575616,user_988d09923a575616_prompt_98e191fa5bded725,7,False,True,Hindi,"Hi, Cristina, I am feeling not good when I ca...",NaN,B1,A2+,train,A school friend,An email,"A friend from your class, Cristina, had an acc..."
37,essay_2932ebd5446803c9,1577952302,2020-01-02 08:05:02,prompt_49f744b86a7de069,user_49e44929bd7f9a27,user_49e44929bd7f9a27_prompt_49f744b86a7de069,3,False,True,Polish,"Hi Adrew, We are going for short holiday next ...",NaN,B2,B1,train,Instructions,A note,Your neighbour is going to look after your hou...
40,essay_2ae41ea2a3873e11,1577952785,2020-01-02 08:13:05,prompt_e3b16d9c3c7b3cc8,user_49e44929bd7f9a27,user_49e44929bd7f9a27_prompt_e3b16d9c3c7b3cc8,3,False,True,Polish,"HI Ana, Thank you for reaching me out. To answ...",NaN,B1+,B1,train,Learning English,An email,"Read this email from your cousin, Ana. Hi, I s..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23200,essay_13d3712c7f8cb49d,1672321925,2022-12-29 13:52:05,prompt_719435a48902a4b5,user_0a88a7f4b4aede69,user_0a88a7f4b4aede69_prompt_719435a48902a4b5,2,False,True,Vietnamese,"Hi teacher, I want to learn something new in r...",NaN,A2+,B1,train,Studying a new subject,A note,You are studying English. You also want to stu...
23202,essay_165aa83b59e618b2,1672322553,2022-12-29 14:02:33,prompt_98e191fa5bded725,user_0a88a7f4b4aede69,user_0a88a7f4b4aede69_prompt_98e191fa5bded725,2,False,True,Vietnamese,"Hi Cristina, I heard about your accident last ...",NaN,B1,B1,train,A school friend,An email,"A friend from your class, Cristina, had an acc..."
23204,essay_55c39e4b67361be9,1672390832,2022-12-30 09:00:32,prompt_e404501e9bbbc094,user_f937ee83399f8d15,user_f937ee83399f8d15_prompt_e404501e9bbbc094,6,False,True,Spanish,"Hello there, As in this magazine is looking ...",NaN,C2+,B1+,dev,Write and Improve,A review,A well-known magazine for English language lea...
23213,essay_c689fa9de0099ed6,1672405848,2022-12-30 13:10:48,prompt_82f61f70f00cce70,user_66b7fe0ceb2d039d,user_66b7fe0ceb2d039d_prompt_82f61f70f00cce70,9,False,True,Vietnamese,"In my opinion, I agree with the statement belo...",NaN,C1+,B2,train,Books and technology,An opinion essay,Should computers and tablets completely replac...
23215,essay_7022cad7218fbf03,1672473905,2022-12-31 08:05:05,prompt_d5dbd9c04a5c932d,user_43a76f3854bac326,user_43a76f3854bac326_prompt_d5dbd9c04a5c932d,2,False,True,Chinese,Music i...,NaN,B2,B2,train,Music in our lives,An article,You have seen this notice in an international ...

In [3]:
df_cefr.columns

Index(['public_essay_id', 'created_epoch', 'created_timestamp',
       'public_prompt_id', 'public_user_id', 'user_prompt',
       'essay_version_num', 'is_first_version', 'is_final_version', 'language',
       'text', 'wi_suspecttokens', 'automarker_cefr_level',
       'humannotator_cefr_level', 'split', 'topic', 'genre', 'prompt'],
      dtype='object')

In [4]:
df_cefr['humannotator_cefr_level'].value_counts()

humannotator_cefr_level
B1+    1073
B1      959
B2      919
A2+     846
B2+     529
C1      370
A2      202
C1+     102
C2       38
A1+      11
A1        1
Name: count, dtype: int64

In [5]:
# visualize the distribution of humannotator_cefr_level with plotly
# keep in CEFR level order
import plotly.express as px
fig = px.histogram(df_cefr, x='humannotator_cefr_level', title='Distribution of Human Annotated CEFR Levels')
fig.update_xaxes(categoryorder='array', categoryarray=['A1', 'A1+','A2', 'A2+', 'B1', 'B1+', 'B2', 'B2+', 'C1', 'C1+', 'C2'])
# chang colour to monochrome and use plotly_white template
fig.update_traces(marker_color='lightgrey', marker_line_color='black', marker_line_width=1.5)
fig.update_layout(template='plotly_white')
fig.show()

# I will use 8 CEFR levels: A2, A2+, B1, B1+, B2, B2+, C1, C1+
### plus levels are retained as their own classes
### drop A1, A1+, and C2

In [7]:
# Drop unwanted levels, keep plus levels as their own classes
drop_levels = ["A1", "A1+", "C2"]
df_cefr = df_cefr[~df_cefr['humannotator_cefr_level'].isin(drop_levels)].copy()

# Check human annotator CEFR level value_counts
order = ['A2', 'A2+', 'B1', 'B1+', 'B2', 'B2+', 'C1', 'C1+']
df_cefr['humannotator_cefr_level'].value_counts().reindex(order)

humannotator_cefr_level
A2      202
A2+     846
B1      959
B1+    1073
B2      919
B2+     529
C1      370
C1+     102
Name: count, dtype: int64

In [8]:
# visualize the distribution of humannotator_cefr_level with plotly
# keep in CEFR level order
import plotly.express as px
fig = px.histogram(df_cefr, x='humannotator_cefr_level', title='Distribution of Human Annotated CEFR Levels')

fig.update_xaxes(categoryorder='array', categoryarray=['A2','A2+','B1','B1+','B2','B2+','C1','C1+'])
# chang colour to monochrome and use plotly_white template
fig.update_traces(marker_color='lightgrey', marker_line_color='black', marker_line_width=1.5)
fig.update_layout(template='plotly_white')
fig.show()

# Check number of topics at each CEFR level

In [9]:
df_cefr.groupby('humannotator_cefr_level')['topic'].nunique()

humannotator_cefr_level
A2     24
A2+    41
B1     45
B1+    46
B2     44
B2+    32
C1     29
C1+    19
Name: topic, dtype: int64

## Number of unique writing prompts (some topics seem to have more than one prompt)

In [10]:
df_cefr.groupby('humannotator_cefr_level')['public_prompt_id'].nunique()

humannotator_cefr_level
A2     25
A2+    44
B1     49
B1+    50
B2     48
B2+    34
C1     30
C1+    20
Name: public_prompt_id, dtype: int64

In [11]:
pd.crosstab(df_cefr['topic'], df_cefr['humannotator_cefr_level'])

humannotator_cefr_level                    A2  A2+  B1  B1+  B2  B2+  C1  C1+
topic
A concert you went to                       0    0   6   42  29   10   5    0
A long calm life or a short intense life?   0    2   0    7  14   30  24   17
A new school year                           7   31  63   49  44    7   6    0
A party                                     4   33  49   14   1    0   0    0
A school friend                             6   44  43    7   2    0   0    0
A special food you like to eat             10   46  38    5   1    1   0    1
A trip to the science museum               15   34  40    8   3    0   0    0
A trip with your class                      2   19  58   16   7    0   0    0
A visit from a friend                      25   46  19    5   4    0   0    0
Banning the use of mobile phones            0    0   1   12  12   34  32    7
Birthdays in your country                   7   52  34    6   3    0   0    0
Books and technology                        0    1   4   39  31   15   6    0
Health or wealth?                           1    4   9   30  30   22   5    0
Healthy living                              1    3   6   39  35   11   6    0
Instructions                               21   49  19    7   3    0   0    0
Learning English                            6   43  59   39  44    9   2    2
Learning a new language                     0    3  10   36  29   14   7    2
Music in our lives                          0    0   1   33  45    8   7    6
My favourite film                           7   32  52   60  36   10   3    0
My favourite season of the year             0    0   4   38  45    6   6    0
Not being able to go to a party             0    1  10   37  51    4   0    0
Sleep                                       4   18  56   18   5    0   1    0
Studying a new subject                      4   41  46    6   1    0   0    0
Telling the truth                           0    1   2   12  18   22  37    7
The Future of Travel                        0    3   8   48  22   13   5    1
The best holiday ever                       0    2   6   47  32    8   6    0
The purpose of television                   0    3  11   45  30    6   7    0
The school of the future                    0    2   7   32  31   15  10    2
What you do in your free time              11   56  26    3   2    0   0    0
What you like to eat                       26   55  17    3   0    0   0    0
Write and Improve                           1    1   9   55  45   43  29   10
Young people and sports                     0    1   3    6   8   25  30   14
Your home town                             18   40  31    5   3    0   0    0
about exercise                              6   38  44   13   2    0   0    0
about having different teachers             0    4   8   42  25   21   3    0
about indoor activities                     3   44  41   13   0    0   0    0
about medical doctors                       0    1   4   18  22   29  23    4
about office design                         0    1   4    9  27   27  22    9
about studying abroad                       0    1   4   32  39   15  10    1
about studying music                        0    0   4   15  31   27  16    8
about university life                       0    1   2   16  19   41  19    4
about using a computer                      8   44  37    9   2    1   0    0
about video games                           1    1  10   36  32   13   8    2
about volunteer work                        0    1   5   11  24   30  25    3
about your free time                        8   42  39   11   2    1   0    0
about zoos                                  0    2  10   39  28   11  10    2

In [12]:
prompt_per_topic_level = df_cefr.groupby(['humannotator_cefr_level', 'topic'])['public_prompt_id'].nunique()
prompt_per_topic_level[prompt_per_topic_level > 1]

humannotator_cefr_level  topic
A2                       A new school year    2
A2+                      A new school year    2
                         Learning English     2
                         My favourite film    2
B1                       A new school year    2
                         Learning English     2
                         My favourite film    2
                         Write and Improve    2
B1+                      A new school year    2
                         Learning English     2
                         My favourite film    2
                         Write and Improve    2
B2                       A new school year    2
                         Learning English     2
                         My favourite film    2
                         Write and Improve    2
B2+                      A new school year    2
                         Write and Improve    2
C1                       Write and Improve    2
C1+                      Write and Improve    2
Name: public_prompt_id, dtype: int64

# Print the prompts for the topics that have more than one prompt in a CEFR level

In [13]:
# First get the topic-level combinations with multiple prompts
multi_prompt = df_cefr.groupby(['humannotator_cefr_level', 'topic'])['public_prompt_id'].nunique()
multi_prompt = multi_prompt[multi_prompt > 1]

# Then filter and show the unique prompts for those combinations
for (level, topic) in multi_prompt.index:
    print(f"\n{'='*50}")
    print(f"CEFR: {level} | Topic: {topic}")
    print('='*50)
    subset = df_cefr[(df_cefr['humannotator_cefr_level'] == level) & (df_cefr['topic'] == topic)]
    for prompt_id, prompt_text in subset.groupby('public_prompt_id')['prompt'].first().items():
        print(f"\nPrompt ID: {prompt_id}")
        print(prompt_text)

==================================================
CEFR: A2 | Topic: A new school year
==================================================

Prompt ID: prompt_91626718bd3e657e
You receive this email from your English pen friend, Matt. _Hi there,_ _It is the end of the holidays and we will start school again on Monday. In this new school year, I need to work very hard because I will have exams. I must improve in Maths and History. And you? You said you want to improve your English. What will you do to improve it? Good luck!_ _Matt_ Write to Matt and tell him what you will do to improve your English in this new school year.

Prompt ID: prompt_e4c497f7613dcf8a
It is the start of a new school year at your school. Your English teacher asks you to write a report about what you want to achieve in this new school year. You should write about: The areas of your learning you are pleased with. The areas of your learning you want to improve. What you will do to achieve your goals.

==================================================
CEFR: A2+ | Topic: A new school year
==================================================

Prompt ID: prompt_91626718bd3e657e
You receive this email from your English pen friend, Matt. _Hi there,_ _It is the end of the holidays and we will start school again on Monday. In this new school year, I need to work very hard because I will have exams. I must improve in Maths and History. And you? You said you want to improve your English. What will you do to improve it? Good luck!_ _Matt_ Write to Matt and tell him what you will do to improve your English in this new school year.

Prompt ID: prompt_e4c497f7613dcf8a
It is the start of a new school year at your school. Your English teacher asks you to write a report about what you want to achieve in this new school year. You should write about: The areas of your learning you are pleased with. The areas of your learning you want to improve. What you will do to achieve your goals.

==================================================
CEFR: A2+ | Topic: Learning English
==================================================

Prompt ID: prompt_58b9f5f522c0a1ba
You have been asked to write a short **article** for your school magazine with the title: _My reasons for learning English_ Describe your reasons for learning English **and** explain why it is important to you. **Write your article.**

Prompt ID: prompt_e3b16d9c3c7b3cc8
Read this email from your cousin, Ana. Hi, I saw your mum yesterday. She told me you are learning English. That<U+2019>s good news! But I want to know why you are studying English. Why is learning the English language important to you? I wish you luck! Ana **Write an email to Ana and answer her question.**

==================================================
CEFR: A2+ | Topic: My favourite film
==================================================

Prompt ID: prompt_79d7b6720d30aa96
Write an email to your English friend. In your email, tell your friend about your favourite film. What kind of film is it? What is it about? Do you think your friend would like the film?

Prompt ID: prompt_de206ba1795e8dc5
What is your favourite film? Write a letter to your pen friend. Explain why you like the film and why you think your pen friend should watch it.

==================================================
CEFR: B1 | Topic: A new school year
==================================================

Prompt ID: prompt_91626718bd3e657e
You receive this email from your English pen friend, Matt. _Hi there,_ _It is the end of the holidays and we will start school again on Monday. In this new school year, I need to work very hard because I will have exams. I must improve in Maths and History. And you? You said you want to improve your English. What will you do to improve it? Good luck!_ _Matt_ Write to Matt and tell him what you will do to improve your English in this new school year.

Prompt ID: prompt_e4c497f7613dcf8a
It is the start of a new school year at your school. Your English teacher asks you to write a report about what you want to achieve in this new school year. You should write about: The areas of your learning you are pleased with. The areas of your learning you want to improve. What you will do to achieve your goals.

==================================================
CEFR: B1 | Topic: Learning English
==================================================

Prompt ID: prompt_58b9f5f522c0a1ba
You have been asked to write a short **article** for your school magazine with the title: _My reasons for learning English_ Describe your reasons for learning English **and** explain why it is important to you. **Write your article.**

Prompt ID: prompt_e3b16d9c3c7b3cc8
Read this email from your cousin, Ana. Hi, I saw your mum yesterday. She told me you are learning English. That<U+2019>s good news! But I want to know why you are studying English. Why is learning the English language important to you? I wish you luck! Ana **Write an email to Ana and answer her question.**

==================================================
CEFR: B1 | Topic: My favourite film
==================================================

Prompt ID: prompt_79d7b6720d30aa96
Write an email to your English friend. In your email, tell your friend about your favourite film. What kind of film is it? What is it about? Do you think your friend would like the film?

Prompt ID: prompt_de206ba1795e8dc5
What is your favourite film? Write a letter to your pen friend. Explain why you like the film and why you think your pen friend should watch it.

==================================================
CEFR: B1 | Topic: Write and Improve
==================================================

Prompt ID: prompt_046678dfe42e3068
Your English teacher told you about Write and Improve and said you should use it to practise and improve your English writing.<U+00A0> Your teacher has asked you to write **a report** about your experience with Write and Improve, describing what you liked or didn<U+2019>t like about it and why. Finish by saying whether you would recommend your classmates to try it. Write your **report**.

Prompt ID: prompt_e404501e9bbbc094
A well-known magazine for English language learners has asked for reviews from readers about useful resources for learning English. You have recently discovered Write and Improve, a new writing tool for learners of English. Write a review for the magazine describing the main features of the tool and why it is/isn<U+2019>t helpful. Include details about what you like about the tool and about any difficulties you had with it, and finish by giving your recommendation for other readers. Write your **review**.

==================================================
CEFR: B1+ | Topic: A new school year
==================================================

Prompt ID: prompt_91626718bd3e657e
You receive this email from your English pen friend, Matt. _Hi there,_ _It is the end of the holidays and we will start school again on Monday. In this new school year, I need to work very hard because I will have exams. I must improve in Maths and History. And you? You said you want to improve your English. What will you do to improve it? Good luck!_ _Matt_ Write to Matt and tell him what you will do to improve your English in this new school year.

Prompt ID: prompt_e4c497f7613dcf8a
It is the start of a new school year at your school. Your English teacher asks you to write a report about what you want to achieve in this new school year. You should write about: The areas of your learning you are pleased with. The areas of your learning you want to improve. What you will do to achieve your goals.

==================================================
CEFR: B1+ | Topic: Learning English
==================================================

Prompt ID: prompt_58b9f5f522c0a1ba
You have been asked to write a short **article** for your school magazine with the title: _My reasons for learning English_ Describe your reasons for learning English **and** explain why it is important to you. **Write your article.**

Prompt ID: prompt_e3b16d9c3c7b3cc8
Read this email from your cousin, Ana. Hi, I saw your mum yesterday. She told me you are learning English. That<U+2019>s good news! But I want to know why you are studying English. Why is learning the English language important to you? I wish you luck! Ana **Write an email to Ana and answer her question.**

==================================================
CEFR: B1+ | Topic: My favourite film
==================================================

Prompt ID: prompt_79d7b6720d30aa96
Write an email to your English friend. In your email, tell your friend about your favourite film. What kind of film is it? What is it about? Do you think your friend would like the film?

Prompt ID: prompt_de206ba1795e8dc5
What is your favourite film? Write a letter to your pen friend. Explain why you like the film and why you think your pen friend should watch it.

==================================================
CEFR: B1+ | Topic: Write and Improve
==================================================

Prompt ID: prompt_046678dfe42e3068
Your English teacher told you about Write and Improve and said you should use it to practise and improve your English writing.<U+00A0> Your teacher has asked you to write **a report** about your experience with Write and Improve, describing what you liked or didn<U+2019>t like about it and why. Finish by saying whether you would recommend your classmates to try it. Write your **report**.

Prompt ID: prompt_e404501e9bbbc094
A well-known magazine for English language learners has asked for reviews from readers about useful resources for learning English. You have recently discovered Write and Improve, a new writing tool for learners of English. Write a review for the magazine describing the main features of the tool and why it is/isn<U+2019>t helpful. Include details about what you like about the tool and about any difficulties you had with it, and finish by giving your recommendation for other readers. Write your **review**.

==================================================
CEFR: B2 | Topic: A new school year
==================================================

Prompt ID: prompt_91626718bd3e657e
You receive this email from your English pen friend, Matt. _Hi there,_ _It is the end of the holidays and we will start school again on Monday. In this new school year, I need to work very hard because I will have exams. I must improve in Maths and History. And you? You said you want to improve your English. What will you do to improve it? Good luck!_ _Matt_ Write to Matt and tell him what you will do to improve your English in this new school year.

Prompt ID: prompt_e4c497f7613dcf8a
It is the start of a new school year at your school. Your English teacher asks you to write a report about what you want to achieve in this new school year. You should write about: The areas of your learning you are pleased with. The areas of your learning you want to improve. What you will do to achieve your goals.

==================================================
CEFR: B2 | Topic: Learning English
==================================================

Prompt ID: prompt_58b9f5f522c0a1ba
You have been asked to write a short **article** for your school magazine with the title: _My reasons for learning English_ Describe your reasons for learning English **and** explain why it is important to you. **Write your article.**

Prompt ID: prompt_e3b16d9c3c7b3cc8
Read this email from your cousin, Ana. Hi, I saw your mum yesterday. She told me you are learning English. That<U+2019>s good news! But I want to know why you are studying English. Why is learning the English language important to you? I wish you luck! Ana **Write an email to Ana and answer her question.**

==================================================
CEFR: B2 | Topic: My favourite film
==================================================

Prompt ID: prompt_79d7b6720d30aa96
Write an email to your English friend. In your email, tell your friend about your favourite film. What kind of film is it? What is it about? Do you think your friend would like the film?

Prompt ID: prompt_de206ba1795e8dc5
What is your favourite film? Write a letter to your pen friend. Explain why you like the film and why you think your pen friend should watch it.

==================================================
CEFR: B2 | Topic: Write and Improve
==================================================

Prompt ID: prompt_046678dfe42e3068
Your English teacher told you about Write and Improve and said you should use it to practise and improve your English writing.<U+00A0> Your teacher has asked you to write **a report** about your experience with Write and Improve, describing what you liked or didn<U+2019>t like about it and why. Finish by saying whether you would recommend your classmates to try it. Write your **report**.

Prompt ID: prompt_e404501e9bbbc094
A well-known magazine for English language learners has asked for reviews from readers about useful resources for learning English. You have recently discovered Write and Improve, a new writing tool for learners of English. Write a review for the magazine describing the main features of the tool and why it is/isn<U+2019>t helpful. Include details about what you like about the tool and about any difficulties you had with it, and finish by giving your recommendation for other readers. Write your **review**.

==================================================
CEFR: B2+ | Topic: A new school year
==================================================

Prompt ID: prompt_91626718bd3e657e
You receive this email from your English pen friend, Matt. _Hi there,_ _It is the end of the holidays and we will start school again on Monday. In this new school year, I need to work very hard because I will have exams. I must improve in Maths and History. And you? You said you want to improve your English. What will you do to improve it? Good luck!_ _Matt_ Write to Matt and tell him what you will do to improve your English in this new school year.

Prompt ID: prompt_e4c497f7613dcf8a
It is the start of a new school year at your school. Your English teacher asks you to write a report about what you want to achieve in this new school year. You should write about: The areas of your learning you are pleased with. The areas of your learning you want to improve. What you will do to achieve your goals.

==================================================
CEFR: B2+ | Topic: Write and Improve
==================================================

Prompt ID: prompt_046678dfe42e3068
Your English teacher told you about Write and Improve and said you should use it to practise and improve your English writing.<U+00A0> Your teacher has asked you to write **a report** about your experience with Write and Improve, describing what you liked or didn<U+2019>t like about it and why. Finish by saying whether you would recommend your classmates to try it. Write your **report**.

Prompt ID: prompt_e404501e9bbbc094
A well-known magazine for English language learners has asked for reviews from readers about useful resources for learning English. You have recently discovered Write and Improve, a new writing tool for learners of English. Write a review for the magazine describing the main features of the tool and why it is/isn<U+2019>t helpful. Include details about what you like about the tool and about any difficulties you had with it, and finish by giving your recommendation for other readers. Write your **review**.

==================================================
CEFR: C1 | Topic: Write and Improve
==================================================

Prompt ID: prompt_046678dfe42e3068
Your English teacher told you about Write and Improve and said you should use it to practise and improve your English writing.<U+00A0> Your teacher has asked you to write **a report** about your experience with Write and Improve, describing what you liked or didn<U+2019>t like about it and why. Finish by saying whether you would recommend your classmates to try it. Write your **report**.

Prompt ID: prompt_e404501e9bbbc094
A well-known magazine for English language learners has asked for reviews from readers about useful resources for learning English. You have recently discovered Write and Improve, a new writing tool for learners of English. Write a review for the magazine describing the main features of the tool and why it is/isn<U+2019>t helpful. Include details about what you like about the tool and about any difficulties you had with it, and finish by giving your recommendation for other readers. Write your **review**.

==================================================
CEFR: C1+ | Topic: Write and Improve
==================================================

Prompt ID: prompt_046678dfe42e3068
Your English teacher told you about Write and Improve and said you should use it to practise and improve your English writing.<U+00A0> Your teacher has asked you to write **a report** about your experience with Write and Improve, describing what you liked or didn<U+2019>t like about it and why. Finish by saying whether you would recommend your classmates to try it. Write your **report**.

Prompt ID: prompt_e404501e9bbbc094
A well-known magazine for English language learners has asked for reviews from readers about useful resources for learning English. You have recently discovered Write and Improve, a new writing tool for learners of English. Write a review for the magazine describing the main features of the tool and why it is/isn<U+2019>t helpful. Include details about what you like about the tool and about any difficulties you had with it, and finish by giving your recommendation for other readers. Write your **review**.

# Sample so that the same learners & topics are not in both train and test sets
### I used "topic" for the topic, not "public_prompt_id"
### also the topic is across CEFR levels
### train/test split is around 80/20 to 85/15 depending on the CEFR level
### test is actually split into val & test
### test will be used right at the very end (val can be used for any finetuning)

In [17]:
import pandas as pd
import numpy as np
from pathlib import Path

# ===============================
# Configuration
# ===============================
RNG_SEED = 20260620
np.random.seed(RNG_SEED)
rng = np.random.default_rng(RNG_SEED)

TARGET_HOLDOUT_RATIO = 0.10

COL_CEFR = "humannotator_cefr_level"
COL_TOPIC = "topic"

CEFR_ORDER = {"A2": 0, "A2+": 1, "B1": 2, "B1+": 3, "B2": 4, "B2+": 5, "C1": 6, "C1+": 7}

df = df_cefr.copy()

print("=== Original distribution ===")
print(df[COL_CEFR].value_counts().sort_index())
print()

# ===============================
# Step 1. Assign topics globally to train vs holdout
# ===============================
topic_sizes = df.groupby(COL_TOPIC).size()
topic_cefr_coverage = df.groupby(COL_TOPIC)[COL_CEFR].apply(set)
all_topics = topic_sizes.index.tolist()
rng.shuffle(all_topics)

target_holdout_per_cefr = {
    cefr: int(len(df[df[COL_CEFR] == cefr]) * TARGET_HOLDOUT_RATIO * 1.3)
    for cefr in CEFR_ORDER
}

holdout_topics = []
holdout_counts = {cefr: 0 for cefr in CEFR_ORDER}

for t in all_topics:
    topic_cefr = topic_cefr_coverage[t]
    needed = any(holdout_counts[c] < target_holdout_per_cefr[c] for c in topic_cefr if c in CEFR_ORDER)
    
    if needed:
        holdout_topics.append(t)
        topic_data = df[df[COL_TOPIC] == t]
        for cefr in topic_cefr:
            if cefr in CEFR_ORDER:
                holdout_counts[cefr] += len(topic_data[topic_data[COL_CEFR] == cefr])

holdout_topics_set = set(holdout_topics)

print(f"Topics: {len(holdout_topics)} holdout, {len(all_topics) - len(holdout_topics)} train")
print("\nHoldout achieved per CEFR:")
for cefr in CEFR_ORDER:
    total = len(df[df[COL_CEFR] == cefr])
    print(f"  [{cefr}] {holdout_counts[cefr]}/{total} ({100*holdout_counts[cefr]/total:.1f}%)")

df["split"] = df[COL_TOPIC].apply(lambda t: "holdout" if t in holdout_topics_set else "train")

# ===============================
# Step 2. Split holdout into val and test
# ===============================
holdout_data = df[df["split"] == "holdout"].copy()
holdout_shuffled = holdout_data.sample(frac=1, random_state=RNG_SEED)

val_idx = []
test_idx = []

for cefr in CEFR_ORDER:
    cefr_data = holdout_shuffled[holdout_shuffled[COL_CEFR] == cefr]
    n_val = len(cefr_data) // 2
    val_idx.extend(cefr_data.iloc[:n_val].index.tolist())
    test_idx.extend(cefr_data.iloc[n_val:].index.tolist())

df.loc[val_idx, "split"] = "val"
df.loc[test_idx, "split"] = "test"

# ===============================
# Step 3. Verification
# ===============================
print("\n=== Verification ===")

train_topics = set(df[df["split"] == "train"][COL_TOPIC])
val_topics = set(df[df["split"] == "val"][COL_TOPIC])
test_topics = set(df[df["split"] == "test"][COL_TOPIC])

if train_topics & val_topics:
    print(f"ERROR: {len(train_topics & val_topics)} topics overlap train/val")
else:
    print("✓ No topic overlap between train and val")

if train_topics & test_topics:
    print(f"ERROR: {len(train_topics & test_topics)} topics overlap train/test")
else:
    print("✓ No topic overlap between train and test")

# ===============================
# Step 4. Final distribution
# ===============================
print("\n=== Final distribution ===")
pivot = df.groupby([COL_CEFR, "split"]).size().unstack(fill_value=0)
pivot = pivot[["train", "val", "test"]]
pivot["total"] = pivot.sum(axis=1)
pivot["train_pct"] = (100 * pivot["train"] / pivot["total"]).round(1)
pivot["val_pct"] = (100 * pivot["val"] / pivot["total"]).round(1)
pivot["test_pct"] = (100 * pivot["test"] / pivot["total"]).round(1)
print(pivot)
print(f"\nTotal: {len(df)}")

print("\n=== Topics per split ===")
for split in ["train", "val", "test"]:
    n = df[df["split"] == split][COL_TOPIC].nunique()
    print(f"{split}: {n} topics")

final_df = df.copy()

=== Original distribution ===
humannotator_cefr_level
A2      202
A2+     846
B1      959
B1+    1073
B2      919
B2+     529
C1      370
C1+     102
Name: count, dtype: int64

Topics: 10 holdout, 36 train

Holdout achieved per CEFR:
  [A2] 60/202 (29.7%)
  [A2+] 273/846 (32.3%)
  [B1] 257/959 (26.8%)
  [B1+] 191/1073 (17.8%)
  [B2] 220/919 (23.9%)
  [B2+] 99/529 (18.7%)
  [C1] 74/370 (20.0%)
  [C1+] 29/102 (28.4%)

=== Verification ===
✓ No topic overlap between train and val
✓ No topic overlap between train and test

=== Final distribution ===
split                    train  val  test  total  train_pct  val_pct  test_pct
humannotator_cefr_level
A2                         142   30    30    202       70.3     14.9      14.9
A2+                        573  136   137    846       67.7     16.1      16.2
B1                         702  128   129    959       73.2     13.3      13.5
B1+                        882   95    96   1073       82.2      8.9       8.9
B2                         699  110   110    919       76.1     12.0      12.0
B2+                        430   49    50    529       81.3      9.3       9.5
C1                         296   37    37    370       80.0     10.0      10.0
C1+                         73   14    15    102       71.6     13.7      14.7

Total: 5000

=== Topics per split ===
train: 36 topics
val: 10 topics
test: 10 topics

# Save to JSONL

In [18]:
import json
import re
from pathlib import Path

out_dir = Path("data")
out_dir.mkdir(exist_ok=True)

def clean_text(t: str) -> str:
    text = str(t)
    text = text.replace("%%", "")
    text = re.sub(r"([.,!?])(?=\S)", r"\1 ", text)
    text = re.sub(r"\s+([.,!?])", r"\1", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

def row_to_json(row):
    result = {
        "id": row["public_essay_id"],
        "text": clean_text(row["text"]),
        "label": row["humannotator_cefr_level"],
        "topic": row["topic"],
        "prompt_id": row["public_prompt_id"],
        "learner_id": row["public_user_id"],
        "language": row["language"],
        "genre": row["genre"],
        "prompt": row["prompt"],
    }
    return result

for split in ["train", "val", "test"]:
    split_df = final_df[final_df["split"] == split]
    out_path = out_dir / f"{split}.jsonl"
    with open(out_path, "w", encoding="utf-8") as f:
        for _, row in split_df.iterrows():
            f.write(json.dumps(row_to_json(row), ensure_ascii=False) + "\n")
    print(f"Saved {out_path} ({len(split_df)} texts)")

# Also save a combined CSV for easy inspection
final_df.to_csv(out_dir / "wai_topic_controlled_train_test.csv", index=False)
print(f"Saved {out_dir / 'wai_topic_controlled_train_test.csv'}")

Saved data\train.jsonl (3797 texts)
Saved data\val.jsonl (599 texts)
Saved data\test.jsonl (604 texts)
Saved data\wai_topic_controlled_train_test.csv

# Check L1 distribution

In [20]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

def plot_stacked_bar_plotly(df, save_path="language_stacked_bar.html"):
    cefr_order = ['A2','A2+','B1','B1+','B2','B2+','C1','C1+']
    split_order = ["train", "val", "test"]
    
    fig = make_subplots(
        rows=1, cols=len(cefr_order),
        subplot_titles=cefr_order,
        shared_yaxes=True,
        horizontal_spacing=0.03
    )
    
    languages = sorted(df["language"].dropna().unique())
    
    # Use a larger color palette that can handle more categories
    colors = px.colors.qualitative.Alphabet[:len(languages)]
    if len(languages) > len(px.colors.qualitative.Alphabet):
        # Cycle through if we have even more
        colors = (px.colors.qualitative.Alphabet * 
                  (len(languages) // len(px.colors.qualitative.Alphabet) + 1))[:len(languages)]
    
    color_map = dict(zip(languages, colors))
    
    languages_reversed = languages[::-1]
    
    for col_idx, cefr in enumerate(cefr_order, start=1):
        sub = df[df["humannotator_cefr_level"] == cefr]
        pivot = sub.groupby(["split", "language"]).size().unstack(fill_value=0)
        pivot_pct = pivot.div(pivot.sum(axis=1), axis=0) * 100
        pivot_pct = pivot_pct.reindex(split_order)
        
        for language in languages_reversed:
            if language in pivot_pct.columns:
                values = pivot_pct[language].values
            else:
                values = [0] * len(split_order)
            
            fig.add_trace(
                go.Bar(
                    x=split_order,
                    y=values,
                    name=language,
                    marker_color=color_map[language],
                    showlegend=(col_idx == 1),
                    legendgroup=language,
                    hovertemplate="%{y:.1f}%<extra></extra>"
                ),
                row=1, col=col_idx
            )
    
    fig.update_layout(
        barmode="stack",
        title="Language Distribution by CEFR Level and Split",
        height=700,
        width=1000,
        legend_title="Language",
        legend_traceorder="reversed"
    )
    fig.update_yaxes(title_text="Percentage (%)", row=1, col=1)
    
    fig.write_html(save_path)
    fig.show()
    print(f"Saved interactive stacked bar chart to {save_path}")
    return fig

fig = plot_stacked_bar_plotly(final_df)

Saved interactive stacked bar chart to language_stacked_bar.html

# Text length

In [21]:
# %%
from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt_tab')

final_df['word_count'] = final_df['text'].apply(lambda x: len(word_tokenize(str(x))))

print("Overall:")
print(f"  Mean: {final_df['word_count'].mean():.1f}")
print(f"  SD:   {final_df['word_count'].std():.1f}")
print(f"  Min:  {final_df['word_count'].min()}")
print(f"  Max:  {final_df['word_count'].max()}")

word_count_stats = (final_df.groupby('humannotator_cefr_level')['word_count']
    .agg(['count', 'mean', 'std', 'min', 'max'])
    .reindex(['A2','A2+','B1','B1+','B2','B2+','C1','C1+'])
    .rename(columns={'count': 'N', 'mean': 'Mean', 'std': 'SD', 'min': 'Min', 'max': 'Max'})
    .round(1))

word_count_stats

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\coope\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

Overall:
  Mean: 168.2
  SD:   86.2
  Min:  31
  Max:  622

                            N   Mean    SD  Min  Max
humannotator_cefr_level
A2                        202   65.5  29.4   31  205
A2+                       846   78.8  35.2   31  312
B1                        959  114.1  52.8   38  425
B1+                      1073  183.5  51.4   50  426
B2                        919  206.9  54.5   62  509
B2+                       529  248.5  65.2  108  606
C1                        370  276.7  72.0  151  622
C1+                       102  302.0  80.2  163  548